#!/bin/bash

RI=raspi-info
UPVER=$(curl -sSL https://raw.githubusercontent.com/mapi68/$RI/master/version)
VERSION=$(dpkg -s $RI | grep '^Version:' | awk '/:/ {print $2}')

install() {
	if [[ `uname -m` = aarch64 ]]; then
		wget -P /tmp/ https://github.com/mapi68/"$RI"/raw/master/"$RI"_latest-64.deb; else
		wget -P /tmp/ https://github.com/mapi68/"$RI"/raw/master/"$RI"_latest-32.deb; fi
	sudo dpkg -i /tmp/"$RI"_latest-*.deb; sudo apt install -f -y; rm /tmp/"$RI"_latest-*
}

if ! [ -f /usr/bin/$RI ]; then
	install
else [[ "$VERSION" -ge "$UPVER" ]]
	echo -e '\e[33m'"You have latest version $VERSION: no need install or update"
	echo -e '\e[0m'
fi
