#!/bin/bash

#################################################################################
#                        _       _        __             _ _       _     _      #
#    _ __ __ _ ___ _ __ (_)     (_)_ __  / _| ___       | (_) __ _| |__ | |_    #
#   | '__/ _` / __| '_ \| |_____| | '_ \| |_ / _ \ _____| | |/ _` | '_ \| __|   #
#   | | | (_| \__ \ |_) | |_____| | | | |  _| (_) |_____| | | (_| | | | | |_    #
#   |_|  \__,_|___/ .__/|_|     |_|_| |_|_|  \___/      |_|_|\__, |_| |_|\__|   #
#                 |_|                                        |___/              #
#                                                                               #
#################################################################################

##### VARIABLES AT BEGINNING FOR CORRECT MEASUREMENT!!!
# Temperature
CPUTEMP=$(cat /sys/class/thermal/thermal_zone0/temp)
#######################################################

clear

# System
echo -e '\e[32m'"`lsb_release -d | awk '/Description:/ {print $2, $3, $4, $5}'`"

# Uptime and load average
echo -e "Load average (1m, 5m, 15m)`uptime | awk -F'[a-z]:' '{ print $2}'`"

# Temperature
#CPUTEMP=$(cat /sys/class/thermal/thermal_zone0/temp)
if [ "$CPUTEMP" -lt  "46000" ]; then
	echo -e '\e[32m'"CPU `vcgencmd measure_temp` ---> LOW TEMPERATURE"'\e[0m'; fi
if [ "$CPUTEMP" -gt  "46000" ] && [ "$CPUTEMP" -lt  "54000" ]; then
	echo -e '\e[33m'"CPU `vcgencmd measure_temp` ---> NORMAL TEMPERATURE"'\e[0m'; fi
if [ "$CPUTEMP" -gt  "54000" ] && [ "$CPUTEMP" -lt  "62000"  ]; then
	echo -e '\e[33m\e[1m'"CPU `vcgencmd measure_temp` ---> NORMAL-HIGH TEMPERATURE"'\e[0m'; fi
if [ "$CPUTEMP" -gt  "62000" ] && [ "$CPUTEMP" -lt  "70000" ]; then
	echo -e '\e[31m'"CPU `vcgencmd measure_temp`---> HIGH TEMPERATURE!"'\e[0m'; fi
if [ "$CPUTEMP" -gt  "70000" ];  then
	echo -e '\e[31m\e[1m'"CPU `vcgencmd measure_temp` ---> PLEASE SHUTDOWN THE SERVER: TEMPERATURE IS VERY HIGH!!!"'\e[0m'; fi

# Check Internet and IP
EXTIP=$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | sed -e 's/^"//' -e 's/"$//')
ping -c 1 google.com &> /dev/null && echo -e "\e[32mInternet connected with IP $EXTIP" || echo -e "\e[31m\e[1mInternet not connected"'\e[0m'
INTERFACE=$(ip -o -f inet addr show | awk '/scope global/ {print $2, $4}')
echo -e '\e[32m'"Internal IP:" $INTERFACE

# File system
echo -e '\e[95m'
df -h | grep -v "tmpfs"
echo -e '\e[0m'

# About date...
echo -e '\e[96m'"Time now is `date +"%H:%M:%S"` in ` timedatectl | awk '/Time zone:/ {print $3, $4, $5}'`"
echo -e "Uptime `uptime -p | sed "s/^[^ ]* //"`"
echo -e '\e[0m'

# Tips and random color for fitglet
TIP=/usr/local/lib/raspi-info/shell-tips
FIGLETCOLOR=`shuf -i91-96 -n1`
echo -e '\e[44m\e[1m'" Shell tip: `shuf -n 1 $TIP` "'\e[0m\e['$FIGLETCOLOR'm'

# Print hostname
figlet `hostname -s`
echo -e '\e[0m'"\c"
