#!/bin/bash

RI=raspi-info
UPVER=$(curl -sSfL https://raw.githubusercontent.com/mapi68/$RI/master/version)
VERSION=$(dpkg -s $RI | grep '^Version:' | awk '/:/ {print $2}')

install() {
	if [[ `uname -m` = aarch64 ]]; then
		wget -P /tmp/ https://github.com/mapi68/"$RI"/raw/master/"$RI"_latest-64.deb; else
		wget -P /tmp/ https://github.com/mapi68/"$RI"/raw/master/"$RI"_latest-32.deb; fi
	sudo apt install -y /tmp/"$RI"_latest-*.deb; rm /tmp/"$RI"_latest-*
}

if [[ "$VERSION" -ge "$UPVER" ]]; then
	echo -e '\e[33m'"You have latest version $VERSION: no need update"
	echo -e '\e[0m'
else install
fi
